name: MODIFY, BUILD AND PUSH TO AZURE
on:
  push:
 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'adopt'
 
    - name: Build image 
      run: | 
        ls
        cd ./OracleDatabase/SingleInstance/dockerfiles
        ./buildContainerImage.sh -v 21.3.0 -x
        
    - uses: azure/docker-login@v1
      with:
         login-server: proyectosii.azurecr.io
         username: ${{ secrets.REGISTRY_USER }}
         password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Tag image 
      run: |
          docker images
          docker tag oracle/database:21.3.0-xe \proyectosii.azurecr.io/proyectosii/database:21.3.0-xe
    - name: Push image to DO Container Registry 
      run: docker push proyectosii.azurecr.io/proyectosii/database:21.3.0-xe
